### PR TITLE
Elastic index template generation & setup fixes

### LINKED ISSUE #68: New Fork Indexes are being created with a replica requirement of 1 when it should be 0
**Describe the bug**
Since we recently rolled over to block 330M, the translator created new indexes, but the fork index is still being created with a required replica of 1, causing the ES cluster to report as unhealthy.

**To Reproduce**
1. Delete all fork indices from Elastic
2. Cause a network fork to be caught by the translator
3. A new index will be created with health marked as yellow due to the lack of a replica index

**Expected behavior**
The replica requirement should be set to 0 at index creation

### LINKED ISSUE #70: Make ES template configurable
## Overview
I would like to make the es creation template configurable for both primary shard and replica counts.

### PR DESCRIPTION
**Pull request by guilledk**
On elastic connector startup when setting up index templates, they where a bit outdated, also not getting generated correctly according to suffix conf (was hardcoded to `$CHAIN_NAME-action-*`), and most importantly fork index settings where not getting applied.

Other changes include remove outdated max int stopBlock setting from config-templates and move a few typing things around.

Fixes #68

### CODE REVIEW

**Comment by guilledk** [comment]
Also cherry-picked a commit from branch `configurable_docs_per_index` which allows that setting to be set by env var.

**Comment by guilledk** [comment]
Just added #70 at request of JT, running tests

**Comment by guilledk** [comment]
Ok tested locally and it seems to be creating all indices with the specified settings, we are ready for review again

**Review by poplexity — APPROVED** [review]
LGTM 👍

**Pull request merged**
